const keywordMap = {
  all_teethers: [
    "newborn teether",
    "infant teether",
    "teethers",
    "infant teether toys",
    "newborn teething toys",
    "newborn teethers",
    "silicone teether",
    "silicone teething",
    "teething toys",
    "infant teething relief",
    "best infant teethers",
    "best teethers for newborns",
    "ring teether",
    "teething ring",
    "best teether for babies in india",
    "best teether for baby in india",
    "best teething toys for infants",
    "bis certified teether",
    "silicone teether safe for baby",
    "made in india teether",
    "baby teether india"
  ],

  books_kit: [
    "tummy time for newborn",
    "newborn and tummy time",
    "newborn on tummy",
    "toys for newborn to 6 months",
    "tummy time",
    "tummy time book",
    "high contrast flashcards",
    "montessori educational toys",
    "montessori teaching toys",
    "montessori toys",
    "infant cloth books",
    "infant cloth book",
    "newborn gift",
    "newborn flashcards",
    "tummy time toys",
    "cloth book",
    "sensory toys for newborns",
    "infant learning toys",
    "newborn high contrast images",
    "high contrast images for infants",
    "infant visual development",
    "high contrast black and white photos",
    "montessori toys for newborns",
    "infant tummy time",
    "soft books for infants",
    "black and white books for newborns",
    "high contrast books",
    "tummy time activities",
    "flashcards",
    "baby shower gifts"
  ],

  all_products: [
    "newborn toys",
    "silicone toys",
    "best toys newborn",
    "toys for 3 month old",
    "nubokind teether",
    "nubokind review",
    "nubokind high contrast books"
  ]
};

export default keywordMap;